# Permalinks
permalink:        pretty

# Setup
title:            'Pavel Dolgov'
tagline:          'Homepage'
description:      'Homepage of <a href="https://keybase.io/zer0main">zer0main</a>'
url:              https://keybase.io/zer0main

author:
  name:           'Pavel Dolgov'
  url:            https://twitter.com/pdolgov99

paginate:         5

version:          3.4.3

github:
  repo:           https://github.com/zer0main/zer0main.github.io
  author:         https://github.com/zer0main

gems:
                  - jekyll-paginate
                  - jekyll-sitemap
