# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Pavel Dolgov'
tagline:          'Homepage'
description:      'Homepage of <a href="https://keybase.io/zer0main">zer0main</a>'
url:              https://keybase.io/zer0main
baseurl:          /

author:
  name:           'Pavel Dolgov'
  url:            https://twitter.com/pdolgov99

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zer0main/zer0main.github.io
  author:         https://github.com/zer0main
